### ISSUE TITLE
EID Exception: The root certificate is incorrect?

### ISSUE THREAD

**Issue by boflor** [KeejOow/eidlib#4]
Hello,

I am experiencing some very strange behaviour on 1 particular PC.
When trying to read an eid card with the software I wrote I get the error message "EID Exception: The root certificate is incorrect"
This only happens on this PC with this software. Using the demo software did read the eid card correctly! Google actually returns zero results for this issue.
The library clearly works (in the demo software and the same PC) and the application I wrote also works (on all other PC's).
I tried installing the latest version of the official eid software but that did nothing. 
I am lost for possible causes of this. Where should I begin to look? 

Kind regards,

**Comment by KrOverdulve** [comment]
Hmm that's strange. Perhaps a reader problem or something? If you initialize the library to allow test cards, is the data read correctly then?

**Comment by boflor** [comment]
I dont have any test cards so I wouldn't know :/
If it were a reader problem, would it still work with the demo app?

**Comment by KrOverdulve** [comment]
Well the library just does not verify the root certificate when you enable test cards. Does not mean you need to test with a test card. Call it a less strict version of the library :-). Just construct your BeID instance by 'new BeID(true)' and show the results.

**Comment by boflor** [comment]
Ok, weird stuff: the beid instance was already initialize with the 'true' parameter.
I managed to solve the problem by putting the getIDAddress call in a try catch block. This not only solved the issue but also allowed that the address was being read. 
Seriously: no idea how that is possible...
